# Full content for all 70 Asia animals
ASIA_CONTENT = {
    # CENTRAL ASIA (15 animals)
    "saiga-antelope": {"desc": "The Saiga Antelope (Saiga tatarica) is one of Asia's most distinctive mammals, recognizable by its oversized, bulbous nose that acts as a natural air conditioner. Native to the vast steppes of Central Asia, these Asian antelopes have roamed Eurasian grasslands since the Ice Age. Standing 60-80 cm at the shoulder, saigas are adapted to extreme temperatures, with their nasal structure warming winter air and cooling summer air. They live in large herds undertaking seasonal migrations across Kazakhstan, Mongolia, and Russia. Their diet consists of grasses, herbs, and shrubs. Saigas can run up to 80 km/h to escape predators. Unfortunately, populations declined dramatically due to poaching for horns valued in traditional medicine.", "high": ["Distinctive oversized nose warms and filters air", "Can run up to 80 km/h across Central Asian steppes", "Ancient species surviving since the Pleistocene epoch", "Populations declined 95% due to poaching", "Undertakes seasonal migrations covering hundreds of kilometers"], "cons": "The Saiga Antelope is Critically Endangered with populations plummeting over 95%. Mass die-offs from bacterial infections combined with poaching for horns have devastated herds. Conservation organizations work with Central Asian governments to establish protected areas and reduce demand for saiga horn in traditional medicine markets."},
    
    "pallass-cat": {"desc": "Pallas's Cat (Otocolobus manul), or manul, is a small wild cat native to Central Asian grasslands. Famous for its flat face, stocky body, and the longest, densest fur of any cat species. Unlike most wild cats, they have round pupils and short legs keeping them low to the ground. They inhabit Mongolia, China, Russia, and Central Asia up to 5,000 meters elevation. These solitary predators hunt pikas, rodents, and birds using excellent camouflage. Their thick coat insulates against extreme temperatures. Though appearing cute, they are fierce predators adapted to harsh climates. Threats include habitat degradation and accidental poisoning from rodent control.", "high": ["Has longest and densest fur of any cat species", "Distinctive flat face and round pupils", "Hunts pikas in high-altitude steppe habitats", "Excellent camouflage with grayish coat", "One of least studied wild cats due to remote habitat"], "cons": "Pallas's Cat is Least Concern but declining. Main threats include habitat degradation from overgrazing, reduction of prey like pikas, and accidental poisoning from rodent control. Conservation focuses on habitat protection and reducing human-wildlife conflict."},
    
    "marco-polo-sheep": {"desc": "The Marco Polo Sheep (Ovis ammon polii) is one of the world's largest wild sheep, named after the explorer who documented them in the Pamir Mountains. These Asian animals inhabit high-altitude regions of Tajikistan, Afghanistan, China, and Pakistan at 3,700-4,800 meters. Renowned for impressive spiral horns growing up to 1.9 meters and weighing over 25 kg. Males use massive horns in dramatic head-butting competitions during rutting season. Thick woolly coats insulate against harsh mountain climate. They graze on grasses, herbs, and shrubs in alpine meadows. Trophy hunting and border conflicts threaten populations.", "high": ["Longest horns of any sheep, reaching 1.9 meters", "Named after Marco Polo from 13th-century travels", "Inhabits extreme high-altitude environments to 4,800m", "Males engage in dramatic head-butting battles", "One of the largest wild sheep species globally"], "cons": "Marco Polo Sheep face threats from trophy hunting, habitat fragmentation from border fences, and competition with livestock. Conservation focuses on sustainable hunting programs and international cooperation among Central Asian nations."},
    
    "bukhara-deer": {"desc": "The Bukhara Deer (Cervus elaphus bactrianus), or Bactrian red deer, is a rare Central Asian subspecies. Once abundant in river valleys of Uzbekistan, Turkmenistan, Tajikistan, and Kazakhstan, they now survive in fragmented populations. Well-adapted to arid environments, they depend on riparian woodlands along the Amu Darya and Syr Darya rivers. Smaller than European cousins with lighter coloring for desert-edge habitats. Males grow impressive antlers shed and regrown annually. They feed on grasses, leaves, shoots, and bark. Extensive hunting and riparian forest destruction reduced their range. Today among Asia's rarest deer with only a few hundred remaining.", "high": ["One of Asia's rarest deer with few hundred remaining", "Depends on riparian forests along Central Asian rivers", "Smaller and lighter-colored than European relatives", "Males grow impressive antlers for mating displays", "Historically ranged across four Central Asian countries"], "cons": "Bukhara Deer are critically endangered due to habitat loss from deforestation and overhunting. Conservation involves captive breeding, habitat restoration, and reintroduction efforts requiring international cooperation."},
    
    "goitered-gazelle": {"desc": "The Goitered Gazelle (Gazella subgutturosa) inhabits deserts and semi-arid regions of Central Asia and the Middle East. Named for the enlarged larynx visible in males during breeding season. Superbly adapted to arid environments, they inhabit sandy deserts and steppes from Kazakhstan to Iran and Mongolia. They can survive long periods without drinking, obtaining moisture from vegetation. Known for distinctive 'rocking horse' running gait. During breeding, males become territorial displaying enlarged throats. They live in small herds feeding on grasses and leaves. Excellent eyesight helps them run up to 60 km/h to escape predators.", "high": ["Named for enlarged larynx males display during breeding", "Survives without drinking, getting moisture from plants", "Distinctive 'rocking horse' gait across desert terrain", "Reaches speeds up to 60 km/h to escape predators", "Inhabits vast range across Central Asian deserts"], "cons": "Goitered Gazelle populations declined significantly from habitat degradation, illegal hunting, and livestock competition. Now vulnerable in many areas. Conservation focuses on protected area management and sustainable land use."},
    
    "siberian-ibex": {"desc": "The Siberian Ibex (Capra sibirica) is a majestic wild goat inhabiting rugged Central Asian mountains. Found in the Himalayas, Pamir, Tian Shan, and Altai mountains across Kazakhstan, Kyrgyzstan, Tajikistan, Mongolia, and China. Among the largest wild goats, males weigh up to 130 kg with magnificent curved horns exceeding one meter. Thick coats range from light brown to grayish for camouflage. Agile climbers navigate steep cliffs with ease, escaping snow leopards and wolves. Live in sex-segregated herds except during mating. Feed on grasses, herbs, and shrubs at high elevations. Trophy hunting impacts some populations.", "high": ["Among largest wild goats with males to 130 kg", "Magnificent curved horns exceed one meter", "Expert climbers navigating steep cliffs", "Lives in sex-segregated herds except mating season", "Important prey for snow leopards and predators"], "cons": "Siberian Ibex face threats from trophy hunting, habitat degradation, and livestock competition. Conservation includes regulated hunting programs and protected area establishment in Central Asian mountains."},
    
    "turkmenian-kulan": {"desc": "The Turkmenian Kulan (Equus hemionus kulan) is an Asiatic wild ass subspecies native to Central Asian arid regions. Once widespread across Turkmenistan, Kazakhstan, and Uzbekistan, now in fragmented populations. Well-adapted to desert life, surviving extended periods without water by obtaining moisture from vegetation. Distinctive sandy-gray coat provides desert camouflage. Standing 1.5 meters at the shoulder, smaller than African cousins but equally hardy. Social animals living in family groups or larger herds. Fast runners reaching 50 km/h to escape predators. Extensively hunted in the 20th century with habitat loss reducing their range.", "high": ["Survives extended periods without water", "Distinctive sandy-gray coat for desert camouflage", "Runs up to 50 km/h to escape predators", "Lives in flexible social groups", "One of Asia's most endangered wild equid subspecies"], "cons": "Turkmenian Kulan is endangered with few thousand remaining. Threats include habitat loss, livestock competition, and limited genetic diversity. Conservation focuses on protected areas and captive breeding programs."},
    
    "caspian-tiger": {"desc": "The Caspian Tiger (Panthera tigris virgata), or Turan tiger, was once the largest tiger subspecies inhabiting Central Asian riverine forests. Ranged from Turkey and Iran through Central Asia to western China. Characterized by narrow, closely-set stripes and brighter golden coat. Males reached 3 meters and over 200 kg. Hunted wild boar and deer in riparian forests along the Amu Darya and Syr Darya. Known for swimming ability, often hunting in wetlands. Faced relentless hunting with bounties paid for kills. Habitat destruction from agriculture eliminated riparian forest homes. Last confirmed individual killed in Turkey in the 1970s.", "high": ["Once largest tiger subspecies exceeding 200 kg", "Had narrow stripes and bright golden coat", "Excellent swimmers hunting in riverine wetlands", "Extinct since 1970s from hunting and habitat loss", "Inhabited vast range from Turkey to western China"], "cons": "The Caspian Tiger is extinct since the 1970s. Discussions about de-extinction through genetic research inform conservation of remaining tiger subspecies across Asia."},
    
    "mongolian-wild-ass": {"desc": "The Mongolian Wild Ass (Equus hemionus hemionus), or Khulan, is native to Mongolian steppes and deserts. Superbly adapted to Gobi Desert's extreme climate, tolerating -40°C to 40°C temperature swings. Reddish-brown summer coat turns thicker and lighter in winter. Social animals living in family groups led by dominant mares. Fast runners reaching 50 km/h with remarkable endurance. Feed on grasses, shrubs, and desert vegetation, traveling long distances for water and food. Important ecological role as grazers. Hunted for meat and hides, facing competition from livestock. Mining and infrastructure development pose additional threats.", "high": ["Survives extreme -40°C to 40°C temperature swings", "Changes coat color seasonally", "Runs up to 50 km/h with endurance", "Lives in family groups led by dominant mares", "Few equid species adapted to true desert conditions"], "cons": "Mongolian Wild Ass is Near Threatened with declining populations from hunting, livestock competition, and habitat degradation. Conservation includes protected areas and community-based management in Gobi regions."},
    
    "asiatic-cheetah": {"desc": "The Asiatic Cheetah (Acinonyx jubatus venaticus) was once widespread across India, Central Asia, and the Middle East. Today survives only in Iran with fewer than 50 individuals. Slightly smaller and paler than African cousins with thicker coat for cooler climates. Distinctive tear marks and non-retractable claws provide traction during high-speed chases. Reach speeds up to 120 km/h, fastest land animals. Hunt gazelles, wild sheep, and ungulates in arid landscapes. Primarily active during day unlike African cheetahs. Hunted extensively by Asian royalty. Iranian government and conservation organizations work to save this iconic predator.", "high": ["World's fastest land animal at 120 km/h", "Fewer than 50 individuals remain in Iran", "Slightly smaller and paler than African cheetahs", "Non-retractable claws for high-speed traction", "Hunted to near extinction by Asian royalty"], "cons": "Asiatic Cheetah is critically endangered with only 12-50 individuals. Threats include habitat loss, prey depletion, road mortality, and limited genetic diversity. Intensive conservation includes protected areas and prey restoration."},
    
    "saker-falcon": {"desc": "The Saker Falcon (Falco cherrug) is a large raptor native to Central Asian grasslands. Prized by falconers for thousands of years in Arab and Central Asian cultures. Among largest falcons with wingspan to 130 cm. Distinctive brown upper body with streaked underparts and pale head. Hunt medium-sized birds and small mammals diving at high speeds. Often nest on ground in grasslands, unique among large falcons. Migrate seasonally with Central Asian populations wintering in southern Asia and Africa. Control rodent and bird populations in steppe ecosystems. Face severe threats from illegal trapping for falconry, habitat degradation, and electrocution on power lines.", "high": ["One of largest falcons with 130 cm wingspan", "Prized by falconers for thousands of years", "Unique ground-nesting behavior among large falcons", "Powerful hunter diving at high speeds", "Migrates seasonally between Central Asia and Africa"], "cons": "Saker Falcon is endangered from illegal trapping, habitat loss, and power line electrocution. Conservation includes artificial nest platforms, anti-poaching, and power line modifications."},
    
    "kulan": {"desc": "The Kulan (Equus hemionus), or Asiatic wild ass, inhabits Central Asian deserts and semi-deserts. Once ranged from Middle East to Mongolia, now in fragmented populations. Well-adapted to arid environments, surviving days without water from vegetation moisture. Distinctive sandy-gray to reddish coat provides camouflage. Standing 1.4 meters at shoulder, larger and more robust than domestic donkeys. Social animals in family groups or larger herds. Fast runners reaching 50 km/h to escape wolves. Feed on grasses, shrubs, and desert plants. Extensively hunted for meat and hides. Habitat loss from agriculture reduced their range. Competition with livestock poses ongoing threats.", "high": ["Survives days without water in deserts", "Larger and more robust than domestic donkeys", "Reaches 50 km/h to escape predators", "Lives in flexible social groups", "Once ranged from Middle East to Mongolia"], "cons": "Kulan is endangered with fragmented populations. Threats include habitat loss, hunting, livestock competition, and limited genetic diversity. Conservation focuses on protected areas and captive breeding."},
    
    "severtsovs-sheep": {"desc": "Severtsov's Sheep (Ovis ammon severtzovi), or Bukhara urial, is a rare argali sheep subspecies native to Central Asian mountains. Named after Russian naturalist Nikolai Severtzov. Inhabit Pamir-Alay mountains of Uzbekistan, Tajikistan, and Kyrgyzstan. Medium-sized wild sheep with males sporting impressive curved horns spiraling outward. Coats range from reddish-brown to grayish for rocky slope camouflage. Agile climbers navigating steep terrain feeding on grasses, herbs, and shrubs. Live in small herds active mornings and afternoons. Rut occurs in autumn with males competing through horn clashes. Face habitat degradation, livestock competition, and poaching. Restricted range makes them vulnerable.", "high": ["Rare subspecies named after Nikolai Severtzov", "Males sport impressive curved spiral horns", "Inhabits Pamir-Alay mountains at high elevations", "Agile climbers on steep rocky terrain", "Restricted range makes them vulnerable"], "cons": "Severtsov's Sheep is vulnerable from restricted range, habitat degradation, and hunting. Conservation includes protected area management and community-based wildlife programs in Pamir-Alay region."},
    
    "eurasian-otter": {"desc": "The Eurasian Otter (Lutra lutra) is semiaquatic with wide distribution across Europe and Asia including Central Asian rivers. Superbly adapted to water with streamlined bodies, webbed feet, and dense waterproof fur. Inhabit rivers, lakes, and coastal areas from western Europe to eastern Russia. Skilled hunters feeding on fish, amphibians, and crustaceans. Use sensitive whiskers to detect prey in murky water, holding breath for several minutes. Solitary animals maintaining territories along waterways marked with scent. Most active dawn and dusk. Important apex predators in freshwater ecosystems. Faced severe declines from hunting for fur and pesticide pollution.", "high": ["Holds breath several minutes hunting underwater", "Uses sensitive whiskers to detect prey", "Dense waterproof fur insulates in cold water", "Maintains territories with scent markings", "Wide distribution from Europe to Central Asia"], "cons": "Eurasian Otter populations in Central Asia face habitat degradation, water pollution, and fishing net entanglement. Asian populations require continued protection of riverine habitats."},
    
    "tien-shan-brown-bear": {"desc": "The Tien Shan Brown Bear (Ursus arctos isabellinus), or Himalayan brown bear, inhabits high Central Asian mountains. Found in Tien Shan, Pamir, and Himalayas across Kyrgyzstan, Tajikistan, Kazakhstan, and northern India. Lighter golden-brown coat provides alpine camouflage. Among Central Asia's largest predators, males weigh up to 200 kg. Omnivorous diet includes grasses, berries, roots, insects, and occasionally livestock. Excellent climbers and diggers using powerful claws. Hibernate in winter dens dug into mountain slopes. Face habitat loss, human-wildlife conflict, and poaching for traditional medicine.", "high": ["Distinctive lighter golden-brown alpine coat", "Largest predator in Central Asian mountains", "Excellent climber and digger with powerful claws", "Hibernates in dens dug into slopes", "Omnivorous diet from plants to livestock"], "cons": "Tien Shan Brown Bear is endangered from habitat loss, human-wildlife conflict, and poaching for traditional medicine. Conservation focuses on protected areas and conflict mitigation."},
}

# EAST ASIA (16 animals)
ASIA_CONTENT.update({
    "red-crowned-crane": {"desc": "The Red-crowned Crane (Grus japonensis), or Japanese crane, is an iconic endangered bird of East Asia. Standing over 1.5 meters tall with wingspan exceeding 2 meters, renowned for elegant appearance and elaborate courtship dances. White plumage contrasted with black necks and wingtips, distinctive red crown patch. Inhabit wetlands, marshes, and coastal areas of Japan, China, Russia, and Korea. Omnivorous, feeding on aquatic plants, insects, fish, and amphibians. Form lifelong pair bonds performing synchronized courtship dances with bowing, leaping, and wing flapping. Symbolize longevity, good fortune, and fidelity in Japanese culture. Habitat loss from wetland drainage severely reduced populations.", "high": ["One of largest cranes standing over 1.5 meters", "Performs elaborate synchronized courtship dances", "Sacred symbol of longevity in Japanese culture", "Distinctive red crown on white and black plumage", "Fewer than 3,000 individuals remain"], "cons": "Red-crowned Crane is endangered with fewer than 3,000 individuals. Threats include wetland habitat loss and agricultural expansion. Conservation success in Japan through artificial feeding provides a model for China and Russia."},
    
    "siberian-tiger": {"desc": "The Siberian Tiger (Panthera tigris altaica), or Amur tiger, is the world's largest cat and iconic East Asian predator. Inhabits Russian Far East, northeastern China, and Korea. Males reach over 3 meters and 300 kg. Thicker, paler coats with fewer stripes adapt to harsh northern winters. Solitary hunters preying on wild boar and red deer in temperate forests. Excellent swimmers patrolling river systems. Require vast territories up to 1,000 square kilometers. Face severe threats from poaching for skins and bones, logging, and prey depletion. Intensive Russian conservation helped stabilize populations.", "high": ["Largest cat species with males to 300 kg", "Thick pale coat for harsh East Asian winters", "Requires vast territories to 1,000 sq km", "Excellent swimmer patrolling rivers", "Fewer than 600 remain in the wild"], "cons": "Siberian Tiger is endangered with 400-600 individuals. Major threats include poaching for traditional medicine and habitat loss. Russian conservation programs show success through anti-poaching and habitat protection."},
    
    "japanese-macaque": {"desc": "The Japanese Macaque (Macaca fuscata), or snow monkey, is the northernmost non-human primate native to Japan. Famous worldwide for bathing in natural hot springs during winter at Jigokudani Monkey Park. Thick brown to gray fur helps survive below -15°C temperatures. Inhabit forests across Japan's main islands from subtropical south to snowy northern mountains. Highly intelligent primates living in large troops with complex social hierarchies. Omnivorous, feeding on fruits, seeds, insects, and bark. Observed using tools and washing food, demonstrating advanced cognition. Cultural behaviors like hot spring bathing pass between generations.", "high": ["Northernmost non-human primate globally", "Famous for bathing in hot springs in winter", "Survives below -15°C with thick fur", "Demonstrates tool use and cultural behavior", "Highly intelligent with complex social hierarchies"], "cons": "Japanese Macaques are Least Concern with stable populations. Habitat fragmentation and human-wildlife conflict in urbanizing areas pose local threats requiring management."},
    
    "amur-leopard": {"desc": "The Amur Leopard (Panthera pardus orientalis) is one of the rarest big cats with fewer than 120 individuals remaining. Inhabits temperate forests of Russian Far East and northeastern China. Thick pale coats with widely spaced rosettes adapt to cold northern climate. Males weigh up to 50 kg, larger than tropical leopards. Solitary predators hunting deer, wild boar, and small mammals. Excellent climbers dragging prey into trees. Require large territories facing habitat loss, poaching, and prey depletion. Small population vulnerable to inbreeding and disease. Land of the Leopard National Park helps stabilize populations.", "high": ["One of rarest big cats with under 120 remaining", "Thick pale coat for cold climate adaptation", "Larger than tropical leopards at 50 kg", "Excellent climber storing prey in trees", "Critically endangered from habitat loss"], "cons": "Amur Leopard is critically endangered with 84-120 individuals. Threats include habitat loss, poaching, and inbreeding. Land of the Leopard National Park and Russia-China cooperation provide hope."},
    
    "red-panda": {"desc": "The Red Panda (Ailurus fulgens) inhabits temperate forests of the Himalayas and southwestern China. Not closely related to giant pandas but belong to unique family Ailuridae. Reddish-brown fur, long bushy tail with red and white rings, masked face with white markings. Size of domestic cat at 3-6 kg. Specialized bamboo feeders also eating fruits, acorns, and eggs. Have pseudo-thumb, extended wrist bone for grasping bamboo. Solitary animals active dawn and dusk, spending time in trees. Inhabit mountain forests at 2,200-4,800 meters. Face habitat loss, fragmentation, and pet trade poaching. Climate change pushes habitat higher reducing range.", "high": ["Not related to giant pandas; unique family Ailuridae", "Has pseudo-thumb for grasping bamboo", "Long bushy tail with red and white rings", "Specialized bamboo feeder in mountain forests", "Faces habitat loss and climate change"], "cons": "Red Panda is endangered with declining population under 10,000. Threats include habitat loss, fragmentation, poaching, and climate change. Conservation focuses on protected areas and community-based forest management."},
    
    "chinese-alligator": {"desc": "The Chinese Alligator (Alligator sinensis), or Yangtze alligator, is one of only two alligator species and only one native to Asia. Found exclusively in lower Yangtze River basin of eastern China. Much smaller than American cousins, rarely exceeding 2 meters. More robust snout fully armored with osteoderms, bony plates in skin. Inhabit slow-moving freshwater including rivers, streams, lakes, and marshes. Opportunistic predators feeding on fish, snails, crustaceans, and small mammals. Nocturnal, spending days in excavated burrows. Hibernate during cold months. Females build mound nests laying 10-50 eggs. Once common throughout eastern China, now critically endangered.", "high": ["One of only two alligator species worldwide", "Only alligator native to Asia", "Much smaller than American alligators", "Fully armored with bony osteoderms", "Builds mound nests laying 10-50 eggs"], "cons": "Chinese Alligator is critically endangered with under 150 wild individuals. Habitat loss from wetland conversion and rice farming devastated populations. Captive breeding programs exist but reintroduction challenges remain."},
    
    "japanese-serow": {"desc": "The Japanese Serow (Capricornis crispus) is a goat-antelope endemic to Japan's mountainous forests. Officially designated a special natural monument in Japan. Medium-sized with stocky build, short legs, and thick woolly coat ranging from black to grayish-brown. Both sexes have short conical horns. Inhabit dense forests and steep mountain slopes on Honshu, Kyushu, and Shikoku islands. Solitary or live in small family groups. Herbivorous, feeding on leaves, shoots, and bark. Excellent climbers navigating steep terrain with sure-footed agility. Important seed dispersers in forest ecosystems. Once hunted extensively, now protected and populations recovered.", "high": ["Endemic to Japan's mountainous forests", "Official special natural monument in Japan", "Both sexes have short conical horns", "Excellent climber on steep terrain", "Important forest seed disperser"], "cons": "Japanese Serow is Least Concern with recovered populations after protection. Once hunted extensively, now stable though habitat fragmentation poses localized concerns."},
    
    "chinese-pangolin": {"desc": "The Chinese Pangolin (Manis pentadactyla) is a scaly anteater native to East Asian forests. One of eight pangolin species worldwide. Covered in overlapping keratin scales providing armor against predators. Roll into tight balls when threatened. Long sticky tongues extend up to 40 cm for eating ants and termites. No teeth, grinding food in muscular stomachs. Solitary and nocturnal, inhabiting forests and grasslands. Excellent diggers creating burrows for shelter. Once widespread across China and neighboring countries. Most trafficked mammal globally due to demand for scales in traditional medicine and meat as delicacy.", "high": ["Covered in overlapping keratin scales for armor", "Rolls into tight ball when threatened", "Long sticky tongue extends to 40 cm", "Most trafficked mammal globally", "No teeth, grinds food in muscular stomach"], "cons": "Chinese Pangolin is critically endangered and functionally extinct in many areas. Massive illegal trafficking for scales and meat devastated populations. Conservation urgently needed with habitat protection and anti-poaching."},
    
    "crested-ibis": {"desc": "The Crested Ibis (Nipponia nippon) is a large white ibis with distinctive red facial skin and crest feathers. Once widespread across East Asia, now nearly extinct in wild. Inhabit wetlands, rice paddies, and forests near water. Feed on fish, frogs, insects, and small aquatic animals using long curved bills. Nests in trees building platform nests of twigs. Known for elegant flight with neck extended and legs trailing. Sacred in Japanese culture but extinct in Japan since 2003. Only wild population survives in Shaanxi Province, China. Intensive conservation efforts including captive breeding aim to prevent total extinction.", "high": ["Distinctive red facial skin and crest feathers", "Once widespread, now nearly extinct in wild", "Sacred in Japanese culture", "Only wild population in Shaanxi, China", "Extinct in Japan since 2003"], "cons": "Crested Ibis is endangered with only one wild population in China. Extinct in Japan, Korea, and Taiwan. Intensive captive breeding and habitat protection aim to prevent total extinction."},
    
    "clouded-leopard": {"desc": "The Clouded Leopard (Neofelis nebulosa) is a medium-sized wild cat native to Himalayan foothills and Southeast Asia forests. Named for distinctive cloud-shaped markings on coat. Short powerful legs, large paws, and exceptionally long tail for balance in trees. Considered evolutionary link between big and small cats. Inhabit tropical and subtropical forests up to 2,500 meters. Arboreal hunters preying on birds, monkeys, deer, and wild boar. Solitary and secretive, rarely seen in wild. Strongest bite relative to body size among cats. Deforestation and poaching for skins and bones threaten populations. Habitat fragmentation isolates remaining populations.", "high": ["Distinctive cloud-shaped coat markings", "Exceptionally long tail for tree balance", "Evolutionary link between big and small cats", "Strongest bite relative to body size", "Arboreal hunter in tropical forests"], "cons": "Clouded Leopard is vulnerable from deforestation, poaching, and habitat fragmentation. Conservation focuses on protected area establishment and anti-poaching in Himalayan and Southeast Asian forests."},
    
    "siberian-musk-deer": {"desc": "The Siberian Musk Deer (Moschus moschiferus) is a small deer species native to East Asian mountain forests. Males possess musk gland producing valuable musk used in perfumery and traditional medicine. Small size at 5-17 kg with long hind legs for climbing steep slopes. No antlers, males have long canine tusks extending from upper jaw. Inhabit coniferous and mixed forests at high elevations. Solitary and nocturnal, feeding on lichens, leaves, and grasses. Excellent climbers navigating steep rocky terrain. Hunted extensively for musk, leading to population declines. Musk can be worth more than gold by weight driving illegal poaching.", "high": ["Males possess valuable musk gland", "Long canine tusks instead of antlers", "Small size with long legs for climbing", "Excellent climber on steep slopes", "Musk worth more than gold by weight"], "cons": "Siberian Musk Deer is vulnerable from extensive hunting for musk. Illegal poaching continues despite protections. Conservation includes musk deer farming to reduce wild harvesting pressure."},
    
    "chinese-giant-salamander": {"desc": "The Chinese Giant Salamander (Andrias davidianus) is the world's largest amphibian reaching 1.8 meters and 60 kg. Native to mountain streams and lakes of central and southern China. Flattened bodies with wrinkled skin ranging from dark brown to black. Poor eyesight, using sensory nodes on head to detect prey vibrations. Carnivorous eating fish, frogs, insects, and crustaceans. Nocturnal, spending days under rocks. Breathe through skin requiring clean, cold, fast-flowing water. Can live over 60 years. Considered delicacy in Chinese cuisine and used in traditional medicine. Habitat destruction and overharvesting devastated wild populations.", "high": ["World's largest amphibian at 1.8 meters", "Can live over 60 years", "Breathes through skin requiring clean water", "Poor eyesight using sensory nodes", "Considered delicacy and medicine in China"], "cons": "Chinese Giant Salamander is critically endangered and functionally extinct in wild. Overharvesting for food and medicine devastated populations. Captive breeding exists but wild recovery unlikely without habitat restoration."},
    
    "siberian-weasel": {"desc": "The Siberian Weasel (Mustela sibirica) is a medium-sized mustelid native to East Asian forests and grasslands. Long slender body with short legs and bushy tail. Rich orange-brown fur with cream to white underside. Black tail tip distinguishes from other weasels. Inhabit forests, grasslands, and agricultural areas from Russia through China to Japan. Agile climbers and swimmers hunting rodents, birds, and eggs. Important rodent controllers in agricultural areas. Sometimes called 'kolinsky' in fur trade, pelts used for paintbrushes. Adaptable to human-modified landscapes. Face hunting for fur and habitat loss in some areas.", "high": ["Rich orange-brown fur with cream underside", "Black tail tip distinguishes from other weasels", "Agile climber and swimmer", "Important rodent controller in agriculture", "Called 'kolinsky' in fur trade for paintbrushes"], "cons": "Siberian Weasel is Least Concern with wide distribution. Hunting for fur and localized habitat loss pose minor threats. Adaptable nature allows persistence in human-modified landscapes."},
    
    "mandarin-duck": {"desc": "The Mandarin Duck (Aix galericulata) is among the world's most beautiful waterfowl native to East Asian forests. Males display spectacular breeding plumage with orange 'sails' on back, purple breast, and striking facial pattern. Females are duller gray-brown for camouflage. Inhabit wooded wetlands, lakes, and streams requiring tree cavities for nesting. Feed on seeds, aquatic plants, insects, and small fish. Pair bonds often last multiple seasons. Males perform elaborate courtship displays. Sacred in Chinese culture symbolizing marital fidelity and happiness. Popular in waterfowl collections worldwide with feral populations established in Europe. Habitat loss threatens native populations.", "high": ["Among world's most beautiful waterfowl", "Males display spectacular breeding plumage", "Sacred in Chinese culture for marital fidelity", "Requires tree cavities for nesting", "Pair bonds often last multiple seasons"], "cons": "Mandarin Duck is Least Concern but populations declining from habitat loss. Popular in collections with feral populations in Europe. Native East Asian populations require forested wetland protection."},
    
    "ussuri-brown-bear": {"desc": "The Ussuri Brown Bear (Ursus arctos lasiotus), or black grizzly, inhabits Russian Far East, northeastern China, and Japan's Hokkaido. Large subspecies with males to 300 kg and dark brown to black fur. Inhabit forests, mountains, and coastal areas. Omnivorous diet including fish, berries, roots, and mammals. Excellent sense of smell detecting food miles away. Hibernate in winter dens dug into hillsides. Important figure in Ainu culture of Hokkaido. Face human-wildlife conflict when raiding crops and livestock. Habitat loss and hunting pressure threaten some populations. Japan's Hokkaido population is largest in East Asia.", "high": ["Large subspecies with males to 300 kg", "Dark brown to black fur", "Excellent sense of smell detecting food miles away", "Important in Ainu culture of Hokkaido", "Hibernates in dens dug into hillsides"], "cons": "Ussuri Brown Bear is Least Concern but populations face hunting pressure and human-wildlife conflict. Hokkaido population is largest and best protected in East Asia."},
    
    "qinling-golden-snub-nosed-monkey": {"desc": "The Qinling Golden Snub-nosed Monkey (Rhinopithecus roxellana qinlingensis) is a rare subspecies endemic to China's Qinling Mountains. Distinctive golden-orange fur, blue faces, and flat snub noses. Inhabit temperate forests at high elevations up to 3,000 meters. Live in large multi-male groups of 100-600 individuals. Feed primarily on lichens, leaves, and bark. Thick fur insulates against cold mountain winters. Endemic to Qinling Mountains with restricted range. Face habitat loss from logging and infrastructure development. Climate change affects food availability. Considered endangered with declining populations.", "high": ["Distinctive golden-orange fur and blue face", "Flat snub nose adaptation to cold", "Lives in large groups of 100-600 individuals", "Endemic to China's Qinling Mountains", "Thick fur insulates against mountain winters"], "cons": "Qinling Golden Snub-nosed Monkey is endangered from habitat loss, climate change, and infrastructure development. Endemic to Qinling Mountains making them vulnerable. Conservation focuses on forest protection."},
})

# SOUTH ASIA (14 animals)
ASIA_CONTENT.update({
    "indian-rhino": {"desc": "The Indian Rhino (Rhinoceros unicornis), or greater one-horned rhinoceros, is the largest rhino species in Asia. Native to grasslands and forests of northern India and Nepal. Can weigh up to 2,700 kg with distinctive single black horn reaching 20-60 cm. Gray-brown skin forms heavy folds giving armored appearance. Excellent swimmers often wallowing in rivers and lakes. Grazers feeding primarily on grasses, leaves, and aquatic plants. Poor eyesight but excellent hearing and smell. Once ranged across northern Indian subcontinent, reduced to small protected areas. Kaziranga National Park holds two-thirds of world population. Conservation success story with populations increasing from 200 to over 3,700.", "high": ["Largest rhino species in Asia at 2,700 kg", "Distinctive single black horn to 60 cm", "Excellent swimmer often wallowing in water", "Gray-brown skin with heavy armor-like folds", "Conservation success: increased from 200 to 3,700"], "cons": "Indian Rhino is vulnerable with over 3,700 individuals. Habitat loss and poaching for horns remain threats. Kaziranga National Park protection led to population recovery, a conservation success story."},
    
    "indian-elephant": {"desc": "The Indian Elephant (Elephas maximus indicus) is a subspecies of Asian elephant native to mainland Asia. Smaller than African elephants with smaller ears and convex backs. Males have tusks, females usually tuskless. Inhabit grasslands, forests, and scrublands across India and Southeast Asia. Highly intelligent with complex social structures led by matriarchs. Communicate through infrasound over long distances. Feed on grasses, bark, leaves, and crops. Play crucial ecological roles as seed dispersers and habitat modifiers. Face severe habitat loss and human-elephant conflict. Often raid crops leading to retaliatory killings. Sacred in Hindu culture associated with Lord Ganesha.", "high": ["Smaller than African elephants with smaller ears", "Males have tusks, females usually tuskless", "Highly intelligent with complex social structures", "Communicates through infrasound over long distances", "Sacred in Hindu culture with Lord Ganesha"], "cons": "Indian Elephant is endangered from habitat loss, fragmentation, and human-elephant conflict. Population approximately 20,000-25,000. Conservation requires habitat corridors and conflict mitigation."},
    
    "snow-leopard": {"desc": "The Snow Leopard (Panthera uncia) is a majestic big cat native to mountain ranges of Central and South Asia. Ghosts of the mountains inhabit alpine zones at 3,000-4,500 meters in Himalayas and Central Asia. Thick smoky-gray fur with dark rosettes provides camouflage against rocky slopes. Long thick tail for balance and wrapping for warmth. Cannot roar due to different vocal cord structure. Solitary hunters preying on blue sheep, ibex, and marmots. Excellent climbers navigating steep cliffs. Require vast territories, home ranges up to 1,000 sq km. Face threats from poaching, habitat loss, and climate change. Retaliatory killings for livestock predation.", "high": ["Ghosts of the mountains in alpine zones", "Thick smoky-gray fur with dark rosettes", "Long thick tail for balance and warmth", "Cannot roar due to vocal cord structure", "Excellent climber on steep cliffs"], "cons": "Snow Leopard is vulnerable with 4,000-6,500 individuals. Threats include poaching, habitat loss, climate change, and retaliatory killings. Conservation focuses on community-based programs and protected areas."},
    
    "indian-peafowl": {"desc": "The Indian Peafowl (Pavo cristatus), or blue peafowl, is among the world's most spectacular birds native to South Asia. Males, called peacocks, display magnificent iridescent blue-green tail feathers with eye-spots. Females, peahens, are duller brown for camouflage. Inhabit forests, grasslands, and agricultural areas across Indian subcontinent. Omnivorous feeding on seeds, insects, small reptiles, and crops. Males perform elaborate courtship displays fanning tail feathers. National bird of India sacred in Hindu culture associated with various deities. Adaptable to human presence, often found near villages and temples. Introduced populations worldwide as ornamental birds.", "high": ["Most spectacular birds with iridescent tail feathers", "Males called peacocks, females peahens", "National bird of India", "Sacred in Hindu culture", "Performs elaborate courtship displays"], "cons": "Indian Peafowl is Least Concern with stable populations. Highly adaptable to human presence. Some conflict with agriculture when feeding on crops. Sacred status provides protection in India."},
    
    "asiatic-lion": {"desc": "The Asiatic Lion (Panthera leo persica) is a lion subspecies surviving only in India's Gir Forest. Smaller than African lions with distinctive skin fold on belly and shorter manes in males. Once ranged from Middle East through India, now restricted to single population. Live in prides though smaller than African lion prides. Hunt deer, antelope, and wild boar. Males weigh up to 190 kg. Critically endangered with approximately 670 individuals. Conservation success increased from 180 in 1974. Face threats from disease, natural disasters, and limited genetic diversity. Single population makes them vulnerable to extinction events.", "high": ["Only survives in India's Gir Forest", "Smaller than African lions with belly skin fold", "Critically endangered with ~670 individuals", "Conservation success: increased from 180", "Single population vulnerable to extinction"], "cons": "Asiatic Lion is endangered with only ~670 individuals in Gir Forest. Single population makes them vulnerable to disease or disaster. Conservation considers establishing second population."},
    
    "indian-jackal": {"desc": "The Indian Jackal (Canis aureus indicus) is a golden jackal subspecies native to Indian subcontinent. Medium-sized canid with golden-yellow to tawny coat and white underparts. Opportunistic omnivores feeding on small mammals, birds, fruits, and carrion. Highly adaptable inhabiting forests, grasslands, and urban areas. Live in pairs or small family groups. Important scavengers cleaning carcasses and controlling rodent populations. Vocal animals with distinctive howling calls. Often seen near human settlements scavenging waste. Feature prominently in Indian folklore and mythology. Generally tolerated near villages though occasionally persecuted.", "high": ["Golden-yellow to tawny coat with white underparts", "Opportunistic omnivore and scavenger", "Highly adaptable to various habitats", "Important scavenger controlling rodents", "Features in Indian folklore and mythology"], "cons": "Indian Jackal is Least Concern with stable populations. Highly adaptable to human presence. Occasionally persecuted but generally tolerated. Important ecological role as scavenger."},
    
    "indian-pangolin": {"desc": "The Indian Pangolin (Manis crassicaudata) is a scaly anteater native to Indian subcontinent. Covered in overlapping brown scales made of keratin. Roll into tight balls when threatened exposing sharp scales. Long sticky tongues extend to 25 cm for eating ants and termites. No teeth, grinding food in muscular stomachs. Nocturnal and solitary inhabiting forests, grasslands, and agricultural areas. Excellent diggers creating deep burrows. Strong claws for breaking into termite mounds. Most trafficked mammal in India for scales and meat. Extensive poaching devastated populations across range.", "high": ["Covered in overlapping keratin scales", "Rolls into tight ball when threatened", "Long sticky tongue extends to 25 cm", "Most trafficked mammal in India", "Excellent digger with strong claws"], "cons": "Indian Pangolin is endangered from extensive poaching for scales and meat. Most trafficked mammal in India. Urgent conservation needed with anti-poaching and habitat protection."},
    
    "nilgiri-tahr": {"desc": "The Nilgiri Tahr (Nilgiritragus hylocrius) is an endangered mountain goat endemic to Western Ghats of southern India. Stocky build with short coarse fur ranging from brown to gray. Males have distinctive light-colored saddle patch on back. Both sexes have curved horns, larger in males. Inhabit cliff faces and grass-covered slopes at 1,200-2,600 meters. Live in herds of 10-100 individuals. Graze on grasses, herbs, and shrubs. Sure-footed climbers navigating steep rocky terrain. Eravikulam National Park holds largest population. State animal of Tamil Nadu. Habitat loss and hunting reduced populations to isolated pockets.", "high": ["Endemic to Western Ghats of southern India", "Males have distinctive light saddle patch", "Sure-footed climber on steep terrain", "State animal of Tamil Nadu", "Largest population in Eravikulam National Park"], "cons": "Nilgiri Tahr is endangered with approximately 3,000 individuals. Habitat loss and hunting reduced populations. Eravikulam National Park provides best protection for largest population."},
    
    "indian-giant-squirrel": {"desc": "The Indian Giant Squirrel (Ratufa indica), or Malabar giant squirrel, is a large tree squirrel endemic to Indian forests. Among largest squirrels at 36 cm body length with tail equally long. Striking multicolored fur with black, brown, cream, and maroon patches. Inhabit tropical forests of peninsular India. Arboreal rarely coming to ground, moving through canopy with leaps up to 6 meters. Build large spherical nests of twigs and leaves in tree forks. Feed on fruits, nuts, flowers, and bark. Solitary or in pairs. Important seed dispersers in forest ecosystems. Deforestation threatens populations in some areas.", "high": ["Among largest squirrels at 36 cm body length", "Striking multicolored fur with multiple colors", "Arboreal rarely coming to ground", "Builds large spherical nests in trees", "Important forest seed disperser"], "cons": "Indian Giant Squirrel is Least Concern but declining from deforestation. Endemic to Indian forests requiring canopy connectivity. Important seed disperser in forest ecosystems."},
    
    "indian-rhinoceros": {"desc": "The Indian Rhinoceros (Rhinoceros unicornis) refers to the greater one-horned rhino populations of the Indian subcontinent. Largest rhino species in Asia with distinctive single horn and armored skin folds. Inhabit grasslands and forests of northern India and Nepal. Excellent swimmers often found in water. Grazers feeding on grasses and aquatic vegetation. Poor eyesight but excellent hearing and smell. Once ranged widely, now restricted to protected areas. Kaziranga National Park holds majority of population. Conservation success increased numbers significantly. Still face poaching for horns valued in traditional medicine.", "high": ["Largest Asian rhino with single horn", "Armored skin folds appearance", "Excellent swimmer often in water", "Kaziranga holds majority of population", "Conservation success story"], "cons": "Indian Rhinoceros is vulnerable with over 3,700 individuals. Poaching for horns and habitat loss remain threats. Kaziranga protection led to significant recovery."},
    
    "indian-flying-fox": {"desc": "The Indian Flying Fox (Pteropus giganteus) is among the world's largest bats native to Indian subcontinent. Wingspan reaches 1.5 meters with fox-like face and large eyes. Nocturnal fruit bats roosting in large colonies of hundreds to thousands. Inhabit forests, agricultural areas, and urban centers. Feed on fruits, nectar, and flowers playing crucial pollination and seed dispersal roles. Excellent vision and sense of smell finding food. Do not use echolocation. Important for forest regeneration and ecosystem health. Sometimes considered pests when raiding orchards. Face habitat loss and hunting for medicine.", "high": ["Among world's largest bats with 1.5m wingspan", "Fox-like face with large eyes", "Nocturnal fruit bat in large colonies", "Important pollinator and seed disperser", "Does not use echolocation"], "cons": "Indian Flying Fox is Least Concern but declining from habitat loss and hunting. Important ecosystem role as pollinator and seed disperser. Sometimes persecuted as crop pest."},
    
    "malabar-civet": {"desc": "The Malabar Civet (Viverra civettina) is a critically endangered viverrid endemic to Western Ghats of India. One of world's rarest mammals with possibly fewer than 250 individuals. Grayish-brown coat with black spots and stripes. Long ringed tail and distinctive facial markings. Nocturnal and solitary inhabiting lowland forests and swamps. Feed on small mammals, birds, frogs, and fruits. Once common in coastal regions, now restricted to fragmented forests. Extensive deforestation and hunting devastated populations. Possibly extinct in wild with no confirmed sightings recently. Intensive surveys needed to determine if any populations survive.", "high": ["Critically endangered with possibly under 250", "Endemic to Western Ghats of India", "Grayish-brown coat with black spots", "One of world's rarest mammals", "Possibly extinct in wild"], "cons": "Malabar Civet is critically endangered and possibly extinct. Extensive deforestation and hunting devastated populations. Intensive surveys needed to locate any surviving individuals."},
    
    "indian-wild-dog": {"desc": "The Indian Wild Dog (Cuon alpinus), or dhole, is a social canid native to Indian forests. Distinctive reddish coat with black-tipped tail and white markings. More social than wolves living in clans of 5-12 individuals. Highly efficient hunters with 80% success rate preying on deer and wild boar. Communicate through whistles and screams rather than barks. Inhabit forests and grasslands of central and southern India. Cooperative hunters capable of taking prey much larger than themselves. Face threats from habitat loss, disease from domestic dogs, and competition with other predators. Sacred in some tribal cultures.", "high": ["Distinctive reddish coat with black-tipped tail", "More social than wolves in clans", "Highly efficient hunters with 80% success", "Communicates through whistles not barks", "Cooperative hunters taking large prey"], "cons": "Indian Wild Dog is endangered with declining populations. Threats include habitat loss, disease from domestic dogs, and competition. Highly social and efficient hunters requiring large territories."},
    
    "indian-crested-porcupine": {"desc": "The Indian Crested Porcupine (Hystrix indica) is a large rodent native to Indian subcontinent and Middle East. Among largest rodents at 60-90 cm length weighing 10-16 kg. Covered in long quills up to 35 cm with distinctive crest of long hairs on neck and shoulders. Nocturnal and terrestrial inhabiting forests, grasslands, and agricultural areas. Feed on roots, tubers, bark, and crops. Excellent diggers creating complex burrow systems. Quills modified hairs with barbed tips for defense. Raise quills and rattle when threatened. Can charge backward impaling predators. Considered pests when raiding crops but important ecosystem engineers.", "high": ["Among largest rodents at 60-90 cm", "Long quills to 35 cm with neck crest", "Excellent digger creating complex burrows", "Raises quills and rattles when threatened", "Important ecosystem engineer"], "cons": "Indian Crested Porcupine is Least Concern with stable populations. Considered agricultural pest in some areas. Important ecosystem role through digging and seed dispersal."},
})

# SOUTHEAST ASIA (15 animals)
ASIA_CONTENT.update({
    "sumatran-orangutan": {"desc": "The Sumatran Orangutan (Pongo abelii) is critically endangered great ape endemic to Sumatra, Indonesia. One of three orangutan species, most endangered with under 14,000 individuals. Distinctive long reddish-brown hair and beard, longer faces than Bornean cousins. Arboreal spending nearly all time in trees, rarely descending to ground. Build nests daily in tree canopy for sleeping. Highly intelligent using tools and solving problems. Share 97% DNA with humans. Males develop large cheek pads and throat pouches at maturity. Face severe threats from palm oil deforestation, logging, and illegal pet trade. Confined to fragmented forest patches in northern Sumatra.", "high": ["Critically endangered with under 14,000", "Endemic to Sumatra, Indonesia", "Arboreal rarely descending to ground", "Builds daily nests in tree canopy", "Shares 97% DNA with humans"], "cons": "Sumatran Orangutan is critically endangered with under 14,000 individuals. Palm oil deforestation is primary threat. Confined to fragmented forests requiring urgent protection and reforestation."},
    
    "malayan-tiger": {"desc": "The Malayan Tiger (Panthera tigris jacksoni) is critically endangered tiger subspecies endemic to Malay Peninsula. Smallest mainland tiger subspecies with males to 120 kg. Orange coat with narrow black stripes provides forest camouflage. Inhabit tropical forests from sea level to mountains. Solitary hunters preying on deer, wild boar, and livestock. Require large territories, males roam up to 100 sq km. Face severe threats from habitat loss, poaching for traditional medicine, and human-tiger conflict. Possibly fewer than 150 individuals remain in wild. National symbol of Malaysia appearing on coat of arms. Urgent conservation needed to prevent extinction.", "high": ["Critically endangered with possibly under 150", "Endemic to Malay Peninsula", "Smallest mainland tiger subspecies", "National symbol of Malaysia", "Solitary hunter requiring large territories"], "cons": "Malayan Tiger is critically endangered with possibly 80-150 remaining. Threats include habitat loss, poaching, and human-tiger conflict. Urgent conservation needed to prevent extinction."},
    
    "komodo-dragon": {"desc": "The Komodo Dragon (Varanus komodoensis) is the world's largest lizard endemic to Indonesian islands. Can reach 3 meters and 70 kg, apex predators in their ecosystem. Inhabit Komodo, Rinca, Flores, and Gili Motang islands. Powerful hunters with venomous bites bringing down deer, pigs, and water buffalo. Forked tongues sense chemicals detecting prey miles away. Can consume 80% body weight in single meal. Parthenogenesis allows females to reproduce without males. Excellent swimmers crossing between islands. Face threats from human encroachment, natural disasters, and climate change. Tourism provides conservation funding but also disturbance.", "high": ["World's largest lizard at 3 meters", "Endemic to Indonesian islands", "Venomous bite brings down large prey", "Can consume 80% body weight in meal", "Parthenogenesis allows female-only reproduction"], "cons": "Komodo Dragon is endangered with 4,000-5,000 individuals. Threats include human encroachment, climate change, and natural disasters. Komodo National Park provides protection."},
    
    "asian-elephant": {"desc": "The Asian Elephant (Elephas maximus) is one of three elephant species native to Southeast Asia. Smaller than African elephants with smaller ears, convex backs, and one finger-like projection on trunk tip. Inhabit forests and grasslands across Southeast Asia. Highly intelligent with complex social structures led by matriarchs. Communicate through infrasound over kilometers. Feed on grasses, bark, leaves, and crops. Play crucial roles as seed dispersers and ecosystem engineers. Face severe habitat loss and fragmentation. Human-elephant conflict common when raiding crops. Domesticated for logging and tourism. Wild population approximately 40,000-50,000 declining rapidly.", "high": ["Smaller than African elephants with smaller ears", "Highly intelligent with matriarch-led societies", "Communicates through infrasound", "Important seed disperser and ecosystem engineer", "Wild population 40,000-50,000 declining"], "cons": "Asian Elephant is endangered with declining populations. Habitat loss, fragmentation, and human-elephant conflict are major threats. Wild populations require urgent protection."},
    
    "proboscis-monkey": {"desc": "The Proboscis Monkey (Nasalis larvatus) is endemic to Borneo's mangrove and riverine forests. Males have distinctive large pendulous noses up to 10 cm long, used to amplify calls. Large monkeys with males to 24 kg, pot-bellied appearance from specialized digestive system. Excellent swimmers with webbed feet crossing rivers regularly. Live in harem groups with one male and multiple females. Feed on leaves, seeds, and unripe fruits. Cannot digest sugars making them specialized folivores. Face severe habitat loss from palm oil plantations and logging. Confined to coastal and riverine forests. Population declined over 50% in past 40 years.", "high": ["Endemic to Borneo's mangrove forests", "Males have large noses up to 10 cm", "Excellent swimmers with webbed feet", "Cannot digest sugars, specialized leaf-eater", "Pot-bellied from specialized digestion"], "cons": "Proboscis Monkey is endangered with declining populations. Habitat loss from palm oil is primary threat. Confined to coastal forests requiring urgent protection."},
    
    "sun-bear": {"desc": "The Sun Bear (Helarctos malayanus) is the smallest bear species native to Southeast Asian forests. Also called honey bear for long tongues extracting honey and insects. Reach only 1.4 meters and 65 kg with short sleek black fur. Distinctive white or orange chest patch shaped like crescent. Arboreal with naked soles and curved claws for climbing. Inhabit tropical forests of Borneo, Sumatra, and mainland Southeast Asia. Omnivorous feeding on fruit, insects, honey, and small vertebrates. Long tongues extend to 25 cm for reaching into hives. Nocturnal and elusive rarely seen. Face severe threats from deforestation and illegal wildlife trade for bear bile farms.", "high": ["Smallest bear species at 1.4 meters", "Called honey bear for long tongue", "Distinctive chest crescent patch", "Arboreal with curved claws for climbing", "Long tongue extends to 25 cm"], "cons": "Sun Bear is vulnerable with declining populations. Deforestation and illegal wildlife trade for bile farms are major threats. Elusive and poorly studied requiring more research."},
    
    "sunda-pangolin": {"desc": "The Sunda Pangolin (Manis javanica) is critically endangered scaly anteater native to Southeast Asia. Covered in overlapping brown scales made of keratin, same material as human nails. Roll into tight balls when threatened. Long sticky tongues extend to 25 cm for eating ants and termites. No teeth, grinding food in muscular stomachs. Arboreal with prehensile tails for climbing. Nocturnal and solitary in tropical forests. Strong claws for breaking into termite mounds. Most trafficked mammal globally for scales and meat. Extensive poaching devastated populations across Southeast Asia. Nearly extinct in many parts of range.", "high": ["Critically endangered scaly anteater", "Overlapping keratin scales for armor", "Rolls into tight ball when threatened", "Most trafficked mammal globally", "Arboreal with prehensile tail"], "cons": "Sunda Pangolin is critically endangered from massive illegal trafficking. Extensive poaching for scales and meat devastated populations. Urgent conservation needed with anti-poaching and demand reduction."},
    
    "bornean-orangutan": {"desc": "The Bornean Orangutan (Pongo pygmaeus) is critically endangered great ape endemic to Borneo. Largest tree-dwelling mammals with males reaching 100 kg. Distinctive reddish-brown hair, males develop large cheek pads and throat pouches. Arboreal spending most time in trees building nests for sleeping. Highly intelligent using tools and solving complex problems. Share 97% DNA with humans. Three subspecies across Borneo face different threats. Feed on fruits, bark, leaves, and insects. Face severe habitat loss from palm oil plantations and logging. Population approximately 100,000 declining rapidly. Rehabilitation centers rescue orphaned individuals.", "high": ["Critically endangered great ape", "Largest tree-dwelling mammals", "Endemic to Borneo", "Highly intelligent using tools", "Shares 97% DNA with humans"], "cons": "Bornean Orangutan is critically endangered with approximately 100,000 declining rapidly. Palm oil deforestation is primary threat. Rehabilitation centers rescue orphaned individuals."},
    
    "clouded-leopard": {"desc": "The Clouded Leopard (Neofelis nebulosa) inhabits Himalayan foothills and Southeast Asian forests. Named for cloud-shaped markings on coat. Short powerful legs, large paws, exceptionally long tail for tree balance. Considered evolutionary link between big and small cats. Inhabit tropical and subtropical forests to 2,500 meters. Arboreal hunters preying on birds, monkeys, deer, and wild boar. Solitary and secretive rarely seen. Strongest bite relative to body size among cats. Deforestation and poaching for skins and bones threaten populations. Habitat fragmentation isolates remaining populations. Two species now recognized: mainland and Sunda clouded leopard.", "high": ["Cloud-shaped coat markings", "Exceptionally long tail for tree balance", "Evolutionary link between cat sizes", "Strongest bite relative to body size", "Arboreal hunter in tropical forests"], "cons": "Clouded Leopard is vulnerable from deforestation, poaching, and habitat fragmentation. Two species now recognized. Conservation focuses on protected areas in Himalayas and Southeast Asia."},
    
    "binturong": {"desc": "The Binturong (Arctictis binturong), or bearcat, is a viverrid native to Southeast Asian forests. Distinctive appearance with black shaggy fur, white whiskers, and prehensile tail. Size of small dog at 60-90 cm weighing 9-14 kg. One of few mammals with prehensile tail for climbing. Inhabit tropical forests of Southeast Asia and Indonesia. Omnivorous feeding on fruit, small animals, and carrion. Important seed dispersers for strangler figs. Nocturnal and arboreal rarely descending. Emit distinctive smell of buttered popcorn from scent glands. Face habitat loss and hunting for meat and pet trade. Declining across range from deforestation.", "high": ["Distinctive black shaggy fur with white whiskers", "Prehensile tail for climbing", "Smells like buttered popcorn", "Important seed disperser for figs", "Called bearcat though not bear or cat"], "cons": "Binturong is vulnerable with declining populations. Habitat loss and hunting for meat and pet trade threaten species. Important seed disperser requiring forest protection."},
    
    "malayan-tapir": {"desc": "The Malayan Tapir (Tapirus indicus) is the only tapir native to Asia, found in Southeast Asian forests. Distinctive black and white pattern provides camouflage in dappled forest light. Largest of four tapir species at 2.5 meters and 350 kg. Short prehensile trunk for grasping leaves and branches. Inhabit tropical forests of Malay Peninsula, Sumatra, and Thailand. Nocturnal and solitary feeding on leaves, shoots, and fruits. Excellent swimmers spending time in water. Important seed dispersers in forest ecosystems. Ancient species little changed for millions of years. Face severe habitat loss from deforestation and hunting. Population fragmented and declining.", "high": ["Only Asian tapir species", "Distinctive black and white pattern", "Largest tapir at 2.5 meters", "Short prehensile trunk for grasping", "Excellent swimmer spending time in water"], "cons": "Malayan Tapir is endangered with fragmented declining populations. Habitat loss from deforestation is primary threat. Ancient species requiring urgent forest protection."},
    
    "banded-palm-civet": {"desc": "The Banded Palm Civet (Hemigalus derbyanus) is a small viverrid native to Southeast Asian forests. Distinctive appearance with long pointed snout, banded coat pattern, and long tail. Size of domestic cat with body to 50 cm. Nocturnal and arboreal inhabiting tropical forests of Malay Peninsula, Borneo, and Sumatra. Feed on insects, small vertebrates, and fruits. Excellent climbers with sharp claws and flexible ankles. Solitary and elusive rarely seen. Important predators controlling insect populations. Face habitat loss from deforestation and palm oil plantations. Poorly studied due to secretive nature. Population declining across range.", "high": ["Distinctive banded coat pattern", "Long pointed snout", "Nocturnal and arboreal", "Excellent climber with flexible ankles", "Important insect predator"], "cons": "Banded Palm Civet is near threatened with declining populations. Habitat loss from deforestation threatens species. Poorly studied requiring more research."},
    
    "malay-tapir": {"desc": "The Malay Tapir (Tapirus indicus) refers to Malayan tapir populations across Southeast Asia. Distinctive black and white pattern like panda of the forest. Largest Asian tapir at 2.5 meters and 350 kg. Short prehensile trunk for grasping vegetation. Inhabit tropical forests and wetlands. Nocturnal and solitary feeding on leaves and fruits. Excellent swimmers often found in water. Important seed dispersers. Ancient species unchanged for millions of years. Face severe habitat loss and hunting. National symbol of Malaysia representing diversity.", "high": ["Panda of the forest with black and white", "Largest Asian tapir", "Prehensile trunk for grasping", "Excellent swimmer", "National symbol of Malaysia"], "cons": "Malay Tapir is endangered from habitat loss and hunting. Ancient species requiring urgent protection. National symbol of Malaysia."},
    
    "siamang": {"desc": "The Siamang (Symphalangus syndactylus) is the largest gibbon species native to Southeast Asian forests. Distinctive throat sac inflates to amplify calls heard kilometers away. Reach 90 cm with arm span to 1.5 meters. Black fur with gray or pink throat sac. Inhabit tropical forests of Malay Peninsula and Sumatra. Highly arboreal brachiating through canopy. Monogamous pairs with complex duet calls defending territories. Feed on leaves, fruit, and insects. Endangered from habitat loss and pet trade. Distinct from other gibbons with fused fingers. Important seed dispersers in forest ecosystems.", "high": ["Largest gibbon species", "Throat sac amplifies calls kilometers away", "Arm span reaches 1.5 meters", "Monogamous pairs with duet calls", "Fused fingers distinguish from gibbons"], "cons": "Siamang is endangered from habitat loss and pet trade. Largest gibbon requiring urgent forest protection. Important seed disperser in Southeast Asian forests."},
    
    "bornean-clouded-leopard": {"desc": "The Bornean Clouded Leopard (Neofelis diardi borneensis) is a distinct species endemic to Borneo. Recently separated from mainland clouded leopard. Smaller with different coat pattern and skull structure. Inhabit tropical forests of Borneo. Arboreal hunters preying on monkeys, deer, and birds. Strongest bite relative to body size. Solitary and secretive rarely seen. Face severe habitat loss from palm oil and logging. Possibly fewer than 10,000 individuals. Confined to protected areas. Urgent conservation needed.", "high": ["Distinct species endemic to Borneo", "Recently separated from mainland species", "Smaller with different coat pattern", "Strongest bite relative to body size", "Arboreal hunter in Borneo forests"], "cons": "Bornean Clouded Leopard is endangered with possibly under 10,000. Habitat loss from palm oil is primary threat. Confined to protected areas requiring urgent conservation."},
})

# WEST ASIA (10 animals)
ASIA_CONTENT.update({
    "arabian-oryx": {"desc": "The Arabian Oryx (Oryx leucoryx) is a magnificent antelope native to Arabian Peninsula deserts. Distinctive white coat with black markings on face and legs, long straight horns. Extinct in wild by 1972 from hunting and habitat loss. Successful reintroduction programs returned them to protected areas. Now live in herds in Saudi Arabia, UAE, Oman, and Israel. Can survive without drinking water obtaining moisture from plants. Adapted to extreme desert temperatures. Important cultural symbol across Arabian Peninsula. Population approximately 1,000 in wild, thousands in captivity. First species to go from extinct in wild to vulnerable status.", "high": ["Extinct in wild by 1972, successfully reintroduced", "Distinctive white coat with black markings", "Can survive without drinking water", "First species to return from extinct in wild", "Important cultural symbol in Arabia"], "cons": "Arabian Oryx is vulnerable with approximately 1,000 in wild. Successful reintroduction model for conservation. Require continued protection from poaching and habitat loss."},
    
    "persian-leopard": {"desc": "The Persian Leopard (Panthera pardus saxicolor) is the largest leopard subspecies native to West Asia. Inhabit mountains and forests of Iran, Afghanistan, Turkey, and Caucasus. Thick fur with widely spaced rosettes for cold climate. Males reach 90 kg, larger than African leopards. Solitary hunters preying on wild sheep, goats, and deer. Excellent climbers storing prey in trees. Require large territories, threatened by habitat loss and poaching. Fewer than 1,000 individuals remain. Iran holds largest population. Important apex predator in mountain ecosystems. Face human-wildlife conflict when preying on livestock.", "high": ["Largest leopard subspecies", "Thick fur for cold mountain climate", "Males reach 90 kg", "Excellent climber storing prey in trees", "Fewer than 1,000 remain"], "cons": "Persian Leopard is endangered with under 1,000 individuals. Iran holds largest population. Threats include habitat loss, poaching, and human-wildlife conflict."},
    
    "arabian-sand-gazelle": {"desc": "The Arabian Sand Gazelle (Gazella marica) is a small antelope native to Arabian deserts. Pale sandy coat provides desert camouflage. Can survive without drinking obtaining moisture from plants. Inhabit sandy deserts and gravel plains of Arabian Peninsula. Live in small herds feeding on desert vegetation. Extremely fast runners reaching 80 km/h. Face habitat loss from development and overgrazing. Reintroduced to protected areas. Population recovering slowly. Important prey for Arabian wolves and leopards.", "high": ["Pale sandy coat for desert camouflage", "Survives without drinking water", "Extremely fast at 80 km/h", "Lives in small desert herds", "Reintroduced to protected areas"], "cons": "Arabian Sand Gazelle is vulnerable with recovering populations. Habitat loss and overgrazing are threats. Reintroduction programs showing success."},
    
    "syrian-brown-bear": {"desc": "The Syrian Brown Bear (Ursus arctos syriacus) is a small bear subspecies native to Middle East mountains. Inhabit Turkey, Iran, Iraq, and Syria. Lighter colored than European brown bears. Smaller size at 100-140 kg. Omnivorous feeding on plants, insects, and small mammals. Face severe habitat loss and hunting. Fewer than 200 individuals remain. Highly fragmented populations. Critically endangered in Syria and Lebanon. Human-wildlife conflict when raiding crops. Important cultural symbol in Middle East.", "high": ["Small bear subspecies of Middle East", "Lighter colored than European bears", "Smaller at 100-140 kg", "Fewer than 200 remain", "Critically endangered in Syria"], "cons": "Syrian Brown Bear is endangered with under 200 individuals. Highly fragmented populations. Threats include habitat loss, hunting, and human-wildlife conflict."},
    
    "caspian-seal": {"desc": "The Caspian Seal (Pusa caspica) is the only marine mammal endemic to the Caspian Sea. Small earless seal with spotted gray coat. Reach 1.5 meters and 50 kg. Feed on fish including kilka and gobies. Breed on winter ice forming in northern Caspian. Can dive to 80 meters for 15 minutes. Face severe threats from pollution, habitat loss, and hunting. Population declined 90% since early 1900s. Fewer than 70,000 remain. Endangered by declining water levels and ice loss. Important indicator of Caspian Sea health.", "high": ["Only marine mammal endemic to Caspian Sea", "Small earless seal with spotted coat", "Can dive to 80 meters for 15 minutes", "Breeds on winter ice", "Population declined 90%"], "cons": "Caspian Seal is endangered with fewer than 70,000. Declined 90% from pollution, hunting, and habitat loss. Climate change reducing ice threatens breeding."},
    
    "blanfords-fox": {"desc": "Blanford's Fox (Vulpes cana) is a small fox native to Middle East and Central Asian mountains. Distinctive appearance with large ears, bushy tail, and gray-brown coat. Inhabit rocky slopes and cliffs in arid regions. Nocturnal feeding on insects, fruit, and small mammals. Excellent climbers navigating steep terrain. Found in Israel, Jordan, Oman, and Afghanistan. Little known due to secretive nature. Face habitat degradation and hunting. Population status poorly understood. Adapted to arid environments with efficient kidneys.", "high": ["Distinctive large ears and bushy tail", "Excellent climber on rocky terrain", "Nocturnal feeding on insects and fruit", "Adapted to arid environments", "Little known due to secretive nature"], "cons": "Blanford's Fox is least concern but status poorly known. Habitat degradation and hunting are threats. Requires more research and monitoring."},
    
    "mountain-gazelle": {"desc": "The Mountain Gazelle (Gazella gazella) is a small antelope native to Middle East mountains. Graceful appearance with slender build and distinctive facial markings. Inhabit mountains and hills of Israel, Jordan, Lebanon, and Turkey. Live in small herds feeding on grasses and shrubs. Extremely agile navigating steep rocky terrain. Can reach speeds of 80 km/h. Face severe habitat loss and hunting. Population declining across range. Important prey for leopards and wolves. National animal of Israel representing wildlife conservation success.", "high": ["Graceful small antelope of Middle East", "Extremely agile on steep terrain", "Can reach 80 km/h", "Distinctive facial markings", "National animal of Israel"], "cons": "Mountain Gazelle is endangered with declining populations. Habitat loss and hunting are major threats. Israel's national animal represents conservation success."},
    
    "arabian-tahr": {"desc": "The Arabian Tahr (Arabitragus jayakari) is a small goat species endemic to Arabian Peninsula mountains. Inhabit steep rocky slopes of Hajar Mountains in Oman and UAE. Males have distinctive long flowing hair on back. Both sexes have backward-curving horns. Excellent climbers navigating cliffs with ease. Feed on grasses, leaves, and shrubs. Face severe habitat loss and hunting. Fewer than 2,500 individuals remain. Confined to mountain protected areas. Important symbol of Arabian wildlife. Climate change threatens high-altitude habitat.", "high": ["Endemic to Arabian Peninsula mountains", "Males have long flowing back hair", "Excellent climber on steep cliffs", "Confined to Hajar Mountains", "Fewer than 2,500 remain"], "cons": "Arabian Tahr is endangered with under 2,500 individuals. Habitat loss and hunting threaten species. Confined to protected mountain areas."},
    
    "arabian-caracal": {"desc": "The Arabian Caracal (Caracal caracal schmitzi) is a caracal subspecies native to Arabian Peninsula. Distinctive appearance with long black tufted ears and sandy coat. Medium-sized cat at 40-50 cm shoulder height. Excellent hunters preying on birds, rodents, and small antelope. Can leap 3 meters to catch birds in flight. Inhabit deserts, mountains, and scrublands. Solitary and nocturnal rarely seen. Face habitat loss and hunting. Population status poorly known. Important predator controlling rodent populations.", "high": ["Distinctive long black tufted ears", "Can leap 3 meters to catch birds", "Excellent hunter of birds and rodents", "Sandy coat for desert camouflage", "Medium-sized cat rarely seen"], "cons": "Arabian Caracal is least concern but status poorly known. Habitat loss and hunting are threats. Important predator requiring monitoring."},
    
    "arabian-wolf": {"desc": "The Arabian Wolf (Canis lupus arabs) is a small wolf subspecies native to Arabian Peninsula. Smallest wolf subspecies adapted to desert environment. Short sandy-gray coat for heat dissipation. Inhabit deserts, mountains, and coastal plains. Live in small packs of 2-4 individuals. Hunt small mammals, birds, and livestock. Face severe persecution from farmers and habitat loss. Population declining across range. Important apex predator in desert ecosystems. Little studied due to rarity. Human-wildlife conflict threatens survival.", "high": ["Smallest wolf subspecies", "Short coat for desert heat dissipation", "Lives in small packs of 2-4", "Hunts small mammals and birds", "Adapted to Arabian desert environment"], "cons": "Arabian Wolf is endangered with declining populations. Persecution from farmers and habitat loss are threats. Little studied requiring urgent research and protection."},
})
